[package]
name = "geodesy-wasm"
version = "0.2.0--alpha1"
authors = ["Sean Rennie <sean.rennie@sensat.co.uk>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "console_log"]

[dependencies]
wasm-bindgen = "0.2.86"

geodesy_rs = { package = "geodesy", git = "https://github.com/busstoptaktik/geodesy.git", rev = "49384de", version = "0.10.0", features = [
  "js",
] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = "0.3.64"
thiserror = "1.0.44"
console_log = { version = "1.0.0", features = ["color"], optional = true }
log = "0.4.19"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
# For tiny binaries
lto = true
