name: Build and Check

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  bindings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Build Dev Wrapper
        run: bun build:wrapper-dev

      - name: Run Wrapper Tests
        run: bun test:wrapper
